name: Schema Check

on: pull_request

jobs:
  echo:
    runs-on: ubuntu-latest

    steps:
      - name: Read schema file
        id: schema
        uses: juliangruber/read-file-action@v1
        with:
          path: ./package.json

      - name: Report schema changes
        uses: fjogeleit/http-request-action@master
        with:
          url: "https://da75c4cc9006.ngrok.io/api/transactions/report"
          method: "POST"
          data: "{ schema: ${{ steps.schema.outputs.content }} }"
