name: Schema Check

on: pull_request

jobs:
  echo:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Read schema file
        id: schema
        run: echo ::set-output name=content::$(cat ./schema.graphql)

      - name: Report schema changes
        uses: fjogeleit/http-request-action@master
        with:
          url: "https://da75c4cc9006.ngrok.io/api/transactions/report"
          method: "POST"
          data: "{ schema: "${{ steps.schema.outputs.content }}" }"
