name: Schema Check

on: pull_request

jobs:
  echo:
    runs-on: ubuntu-latest

    steps:
      - uses: pCYSl5EDgo/cat@master
        id: schema
        with:
          path: schema.graphql

      - uses: fjogeleit/http-request-action@master
        with:
          url: "https://da75c4cc9006.ngrok.io/api/transactions/report"
          method: "POST"
          data: "{ schema: ${{ steps.schema.outputs.text }} }"
